unbind r
bind r source-file ~/.tmux.conf

# Mouse mode for easier window interaction
set -g mouse on

# Prefix to Ctrl-s 
set -g prefix C-s

# History limit 10000 for mouse scrollback
set -g history-limit 100000

# Vim mode
setw -g mode-keys vi

# Vim motions
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
